services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_DB: tofudb
      POSTGRES_USER: tofu_user
      POSTGRES_PASSWORD: your_secure_password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tofu_user -d tofudb"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_USER: tofu_user
      DB_HOST: db
      DB_DATABASE: tofudb
      DB_PASSWORD: your_secure_password
      DB_PORT: 5432
      NODE_ENV: production
      PORT: 8080
    ports:
      - "8080:8080"
    command: npm start

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    depends_on:
      - api
      - db
    environment:
      DATABASE_URL: postgresql://tofu_user:your_secure_password@db:5432/tofudb
      DJANGO_SETTINGS_MODULE: config.settings
      DJANGO_SECRET_KEY: your_secure_django_secret
    ports:
      - "8000:8000"

volumes:
  postgres_data: